### ISSUE TITLE
Use arrow functions to improve samples code

### ISSUE THREAD

**Issue by elsassph** [openfl/openfl-js#1]
In ES6/TypeScript you can improve you samples by using arrow functions - these functions maintain the scope of `this` references:

1. Event handlers
```
obj.addEventListener('foo', this.handler.bind(this));
...
private hander(event) {...}
```
Should be written:
```
obj.addEventListener('foo', this.handler);
...
private hander = (event) => {...}
```

2. Anonymous function scope
```
var self = this;
obj.addEventListener('foo', function(event) {
    self.something();
});
```
Should be written:
```
obj.addEventListener('foo', (event) => {
    this.something();
});
```

**Comment by jgranick** [comment]
Thanks! I changed a few yesterday (before I saw your issue) but I missed a few more. I'll do this Monday

**Comment by jgranick** [comment]
Nevermind, did it now as I realized the released package stripped all the generated JS files 😊

**Comment by jgranick** [comment]
I just reverted the class-level arrow functions (for event listeners) because Webpack would fail to build the project properly. I don't know what loader Webpack uses by default, and whether it is possible to fix support for this syntax easily, without swapping everything out for a Babel config. Maybe you know an easy way to do this?

**Comment by elsassph** [comment]
Adding Babel loader in the Webpack config should be easy enough - it's in every single Webpack boilerplate.
